#!/bin/sh
/usr/bin/logger -t $(/usr/bin/basename $0) "custom script started [$$]"
finish()  {
  /usr/bin/logger -t $(/usr/bin/basename $0) "custom script ended [$$]"
}
trap finish EXIT
  
WANIF="$1"
IPADDR=$(/usr/sbin/nvram get lan_ipaddr)
NETWORK=${IPADDR%.*}

# redirect DNS requests to use the router DNS server
/usr/sbin/iptables -t nat -I PREROUTING -i br0 -s ${NETWORK}.0/24 -p tcp --dport 53 -j DNAT --to-destination ${IPADDR}
/usr/sbin/iptables -t nat -I PREROUTING -i br0 -s ${NETWORK}.0/24 -p udp --dport 53 -j DNAT --to-destination ${IPADDR}

# redirect NTP requests to use the router NTP server
/usr/sbin/iptables -t nat -I PREROUTING -i br0 -s ${NETWORK}.0/24 -p tcp --dport 123 -j DNAT --to-destination ${IPADDR}
/usr/sbin/iptables -t nat -I PREROUTING -i br0 -s ${NETWORK}.0/24 -p udp --dport 123 -j DNAT --to-destination ${IPADDR}
