#!/bin/sh
/usr/bin/logger -t $(/usr/bin/basename $0) "custom script started [$$]"
finish()  {
  /usr/bin/logger -t $(/usr/bin/basename $0) "custom script ended [$$]"
}
trap finish EXIT
  
sleep 5

# set router clock to the time of last system shutdown plus 48 seconds
[ -f /jffs/clock-saved ] && CLOCK="$(/bin/cat /jffs/clock-saved)" && SECONDS=${CLOCK#*.} && SECONDS=${SECONDS#*0} && /bin/date -u -s ${CLOCK%.*}.$(($SECONDS + 48))   # && /usr/sbin/nvram set ntp_ready=1

# create mount points for fstab
/bin/mkdir -p /tmp/mnt/data
/bin/chown $(/usr/sbin/nvram get http_username):root /tmp/mnt/data
/bin/chmod a+rwx /mnt/data

/bin/mkdir -p /tmp/mnt/usbflash
/bin/chown $(/usr/sbin/nvram get http_username):root /tmp/mnt/usbflash
/bin/chmod a+rwx /mnt/usbflash
