#!/bin/sh
/usr/bin/logger -t $(/usr/bin/basename $0) "custom script started [$$]"
finish()
{
  /usr/bin/logger -t $(/usr/bin/basename $0) "custom script ended [$$]"
}
trap finish EXIT
  
DEVICE_PATH="$1"
# optionally allow the pre-mount script to be called manually; specify passphrase type and value on command line
KEY_TYPE="$2"
KEY_VALUE="$3"


mount_swap()
{
  local luks_uuid="$1"
  local mappername="swap-${luks_uuid}"
  
  if [ -b /dev/mapper/$mappername ]; then
    /sbin/swapoff /dev/mapper/$mappername
    /sbin/cryptsetup luksClose $mappername
  fi
  
  passphrase="$(/usr/bin/tr -cd !-~ < /dev/urandom | /usr/bin/head -c 50)"
  /bin/echo -n "$passphrase" | /sbin/cryptsetup --cipher=aes-cbc-essiv:sha256 --key-size=256 --batch-mode --uuid=$luks_uuid luksFormat $DEVICE_PATH
  /bin/echo -n "$passphrase" | /sbin/cryptsetup --batch-mode luksOpen $DEVICE_PATH $mappername
  passphrase="" # forget about it
  /sbin/mkswap /dev/mapper/$mappername
  /sbin/swapon /dev/mapper/$mappername
}                                                                                                                                                   
                                                                                                                                                    
mount_data()
{
  local luks_uuid="$1"
  local mountname="$2"
  local passphrase="$3"
  local passtype="$4"
  local mappername="data-${luks_uuid}"
  local result_unlock=1
  
  if [ ! -d "/mnt/$mountname" ]; then
   /bin/mkdir -p /mnt/$mountname 
   /bin/chown $(/usr/sbin/nvram get http_username):root /mnt/$mountname 
   /bin/chmod a+rwx /mnt/$mountname
  fi
  
  if [ -b /dev/mapper/$mappername ]; then
    /bin/umount /dev/mapper/$mappername
    /sbin/cryptsetup luksClose $mappername
  fi
  
  if [ "$passtype" == "file" ]; then
    if [ -f "$passphrase" ]; then
      /sbin/cryptsetup --batch-mode luksOpen $DEVICE_PATH $mappername < "$passphrase"
      result_unlock=$?
      /bin/rm -f "$passphrase"
    else
      /usr/bin/logger -t $(/usr/bin/basename $0) "custom script passphrase file '$passphrase' was not found [$$]" 
    fi
  elif [ "$passtype" == "text" ]; then
    /bin/echo -n "$passphrase" | /sbin/cryptsetup --batch-mode luksOpen $DEVICE_PATH $mappername
    result_unlock=$?
  else
    /usr/bin/logger -t $(/usr/bin/basename $0) "custom script passphrase type '$passtype' was not recognized [$$]" 
  fi

  passphrase="" # forget about it
  
  if [ $result_unlock -eq 0 ]; then
    /bin/mount /dev/mapper/$mappername && /jffs/scripts/post-mount /tmp/mnt/$mountname
  fi
}

/sbin/modprobe dm-mod
/sbin/modprobe dm-crypt
/sbin/modprobe gf128mul
/sbin/modprobe xts
/sbin/modprobe sha256_generic

/sbin/cryptsetup isLuks $DEVICE_PATH

if [ $? == 0 ]; then

  LUKS_UUID=$(/sbin/cryptsetup luksUUID $DEVICE_PATH)

  case "$LUKS_UUID" in
  
    "11111111-1111-1111-1111-111111111111" )
      mount_swap "$LUKS_UUID"
      ;;
      
    "22222222-2222-2222-2222-222222222222" )
      if [ -z "$KEY_TYPE" ] || [ -z "$KEY_VALUE" ]; then
        KEY_TYPE="file"
        KEY_VALUE="/tmp/passphrase.key"
      fi
      mount_data "$LUKS_UUID" "data" "$KEY_VALUE" "$KEY_TYPE"
      ;;
    
    "33333333-3333-3333-3333-333333333333" )
      mount_data "$LUKS_UUID" "usbflash" "lol" "text"
      ;;
    
    *)
    
      /usr/bin/logger -t $(/usr/bin/basename $0) "custom script LUKS_UUID=$LUKS_UUID was not recognized [$$]"
      ;;
      
  esac

else

  /usr/bin/logger -t $(/usr/bin/basename $0) "custom script device $DEVICE_PATH was not recognized [$$]"
  
fi
