#!/bin/sh
/usr/bin/logger -t $(/usr/bin/basename $0) "custom script started [$$]"
finish()  {
  /usr/bin/logger -t $(/usr/bin/basename $0) "custom script ended [$$]"
}
trap finish EXIT
  

umount_swap()
{
  local luks_uuid="$1"
  local mappername="swap-${luks_uuid}"
  
  if [ -b /dev/mapper/$mappername ]; then
    /sbin/swapoff /dev/mapper/$mappername
    /entware/sbin/cryptsetup luksClose $mappername
  fi
}

umount_data()
{
  local luks_uuid="$1"
  local mappername="data-${luks_uuid}"
  
  if [ -b /dev/mapper/$mappername ]; then
    /bin/umount /dev/mapper/$mappername
    /entware/sbin/cryptsetup luksClose $mappername
  fi
}

# stop Entware-ng
if [ -f /opt/etc/init.d/rc.unslung ]; then
  cd /
  source /opt/etc/init.d/rc.unslung stop
fi

# stop Samba to release locked files
/sbin/service stop_samba

# unmount the encrypted partitions and the swap partition
umount_swap "11111111-1111-1111-1111-111111111111"
umount_data "22222222-2222-2222-2222-222222222222"
umount_data "33333333-3333-3333-3333-333333333333"

# save clock
/bin/date -u +%Y%m%d%H%M.%S > /jffs/clock-saved
